FROM php:7.2
MAINTAINER Nattapon Pondongnok nainatjab999@gmail.com
RUN apt-get update -y && apt-get install -y openssl zip unzip git \
&& curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer \
&& docker-php-ext-install pdo mbstring pdo_mysql \
&& alias pa="php artisan"

WORKDIR /app
COPY . /app

RUN composer install

CMD php artisan serve --host=0.0.0.0 --port=8000
EXPOSE 8000
